name: deploy_to_dev

on:
  workflow_dispatch:
  #   inputs:
  #     tags:
  #       description: "Deploy to dev"
  push:
    branches: [dev,feat/acp-837]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 099635904996.dkr.ecr.ap-southeast-1.amazonaws.com
          ECR_REPOSITORY: acp-x402-server
          IMAGE_TAG: dev
          NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
        run: |
          docker build --build-arg NPM_REGISTRY_TOKEN=$NPM_REGISTRY_TOKEN -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


      # - name: Force deployment (dev-acp-x402-server)
      #   run: |
      #     aws ecs update-service --cluster dev-protocol-be --service dev-acp-x402-server --force-new-deployment
